package ruleasm;

import jade.gui.GuiEvent;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/*
 * Principal.java
 *
 * Re-Created on 18 de febrero de 2025, 08:11 AM
 */
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  Virgilio
 */
public class Principal extends javax.swing.JFrame
{

    public Administrador myAgent;
    public GuiEvent ge;
    public String Motor;
    public String NumR;
    String tipoV, numP, size, numR, motor, vehiculo, volar, tipoMotor;

    /** Creates new form Principal */
    public Principal(Administrador parameter)
    {
        myAgent = parameter;
        initComponents();
        centrarPantalla(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDP1 = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        AgentMessage = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejemplo de Rule <<Vehiculos>>");

        jDP1.setBackground(java.awt.Color.white);

        jInternalFrame1.setTitle("Output Agent Message");
        jInternalFrame1.setVisible(true);

        AgentMessage.setColumns(20);
        AgentMessage.setRows(5);
        jScrollPane1.setViewportView(AgentMessage);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDP1.add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 300, 700, 160);

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Conocimiento");

        jMenuItem2.setText("Iniciar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDP1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDP1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void lanzaVehiculo(String vehiculo)
    {
        if (vehiculo != null)
        {
            JOptionPane.showMessageDialog(this, "Vehiculo= " + vehiculo);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Revisa los datos", "Sin Resutado", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void lanzaFrame(String TipoV)
    {
        if (TipoV != null)
        {
            JOptionPane.showMessageDialog(this, "Tipo de Vehiculo: " + TipoV);
            if (TipoV.equals("cycle"))
            {

                CyclicFrame frame = new CyclicFrame(this, TipoV);
                jDP1.add(frame);
                centrarPantallaInterna(frame);
            }
            if (TipoV.equals("automobile"))
            {
                AutoFrame frame = new AutoFrame(this, TipoV);
                jDP1.add(frame);
                centrarPantallaInterna(frame);
            }
            else
            {
                AereoFrame frame = new AereoFrame(this, TipoV);
                jDP1.add(frame);
                centrarPantallaInterna(frame);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Verifique sus Entradas", "Sin Resultado", JOptionPane.ERROR);
        }
    }

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        TipoVFrame frame = new TipoVFrame(this);
        jDP1.add(frame);
        centrarPantallaInterna(frame);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void centrarPantalla(JFrame ventana)
    {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = ventana.getSize();
        if (frameSize.height > screenSize.height)
        {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width)
        {
            frameSize.width = screenSize.width;
        }
        ventana.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        ventana.setVisible(true);
    }

    public static void PrintMessage(String message)
    {
        AgentMessage.setText(AgentMessage.getText() + message + "\n");
    }

    public void centrarPantallaInterna(JInternalFrame ventana)
    {
        Dimension screenSize = jDP1.getSize();
        Dimension frameSize = ventana.getSize();
        if (frameSize.height > screenSize.height)
        {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width)
        {
            frameSize.width = screenSize.width;
        }
        ventana.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2 - 50);
        ventana.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    static javax.swing.JTextArea AgentMessage;
    private javax.swing.JDesktopPane jDP1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
